version: '3'
tasks:
  default:
    desc: Run tests and linting
    deps:
      - lint-fix
      - test

  generate:
    desc: Generate code
    run: once
    cmds:
      - go generate ./...

  check:
    desc: Generate, lint, and test (CI entrypoint)
    deps:
      - lint
      - test

  test:
    desc: Run library tests
    deps:
      - generate
    cmds:
      - go test -race ./... -test.timeout=3s -count=1

  cover:
    desc: Run tests with cover report
    deps:
      - generate
    cmds:
      - mkdir -p coverage/
      - go test -coverpkg=./... -coverprofile=coverage/cover.out ./... -test.timeout=2s
      - go tool cover -html coverage/cover.out -o coverage/cover.html

  lint:
    desc: Run golangci-lint
    deps:
      - generate
    cmds:
      - golangci-lint run

  lint-fix:
    desc: Run golangci-lint with auto-fix
    deps:
      - generate
    cmds:
      - golangci-lint run --fix

  doc:
    desc: Run pkgsite
    cmds:
      - go tool golang.org/x/pkgsite/cmd/pkgsite
