name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ ".", "inspect" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ format('{0}/go.mod', matrix.module) }}
          cache: true

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: ${{ matrix.module }}
          args: --timeout=2m

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ ".", "inspect" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ format('{0}/go.mod', matrix.module) }}
          cache: true

      - name: Run tests
        run: cd ${{ matrix.module }} && go test -race ./...

  ci:
    name: CI
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - run: echo ok
